### ISSUE TITLE
Method/Function Duplicative

### ISSUE THREAD

**Issue by ericgolftourney** [andyplak/events-manager-pro-paypal-chained-payments#8]
events-manager-pro-pp-chained-payments.php file is giving me a PHP notice that the class and method "EM_Pro_PayPal_Chained" is the same. 

Here is the notice:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; EM_Pro_PayPal_Chained has a deprecated constructor in /wp-content/plugins/events-manager-pro-paypal-chained-payments-master/events-manager-pro-pp-chained-payments.php on line 13

What is the proper way for me to overwrite the class and/or function on line 13 and then at the bottom of the file as well.

**Comment by andyplak** [comment]
@ericgolftourney thanks for raising this. The latest commit should prevent the notice.

**Comment by ericgolftourney** [comment]
Looks great. Thanks, Andy!
